require:
  - rubocop-capybara
  - rubocop-rails

AllCops:
  TargetRubyVersion: 3.2
  DisplayCopNames: true
  NewCops: enable
  Exclude:
    - "vendor/**/*"

Rails:
  Enabled: true

Style/Documentation:
  Enabled: false

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: consistent_comma

# rails default files things
Layout/LineLength:
  Exclude:
    - bin/bundle

Metrics/BlockLength:
  Exclude:
    - config/environments/development.rb

Metrics/CyclomaticComplexity:
  Exclude:
    - bin/bundle

Metrics/MethodLength:
  Exclude:
    - bin/bundle

Metrics/PerceivedComplexity:
  Exclude:
    - bin/bundle

Rails/SkipsModelValidations:
  Exclude:
    - db/migrate/20240401075141_add_service_name_to_active_storage_blobs.active_storage.rb
