name: Deploy

on:
  push:
    branches:
      - main

jobs:
  tag:
    name: "Tag: Production"
    uses: gmmcal/gmmcal-reusable-workflows/.github/workflows/_tag.yml@v0
    concurrency:
      group: tag
      cancel-in-progress: false
    with:
      reference: ${{ github.sha }}

  release:
    name: Release
    uses: gmmcal/gmmcal-reusable-workflows/.github/workflows/_release.yml@v0
    secrets: inherit
    needs: tag
    with:
      tag: ${{needs.tag.outputs.version}}
      reference: ${{ github.sha }}

  build_production:
    name: Build
    uses: gmmcal/gmmcal-reusable-workflows/.github/workflows/_docker.yml@v0
    needs:
      - tag
    secrets: inherit
    with:
      name: Production
      target: production
      reference: ${{needs.tag.outputs.version}}
      image: "gmmcal/ynab:${{needs.tag.outputs.version}},gmmcal/ynab:production"

  build_development:
    name: Build
    uses: gmmcal/gmmcal-reusable-workflows/.github/workflows/_docker.yml@v0
    secrets: inherit
    concurrency:
      group: build-development
      cancel-in-progress: true
    with:
      name: Development
      target: development
      image: "gmmcal/ynab:development"
