name: Pipeline

on:
  - pull_request

concurrency:
  group: pull-request-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  # DOCKER
  build:
    name: Build Image
    uses: gmmcal/gmmcal-reusable-workflows/.github/workflows/_docker.yml@v1
    secrets:
      dockerhub-username: ${{ secrets.DOCKERHUB_USERNAME }}
      dockerhub-token: ${{ secrets.DOCKERHUB_TOKEN }}
    with:
      name: Test
      image: "gmmcal/ynab:test-${{ github.event.number }}-${{ github.run_number }}"

  development:
    name: Build Image
    uses: gmmcal/gmmcal-reusable-workflows/.github/workflows/_docker.yml@v1
    secrets:
      dockerhub-username: ${{ secrets.DOCKERHUB_USERNAME }}
      dockerhub-token: ${{ secrets.DOCKERHUB_TOKEN }}
    with:
      name: Development
      target: development
      publish: false
      image: gmmcal/ynab:development

  production:
    name: Build Image
    uses: gmmcal/gmmcal-reusable-workflows/.github/workflows/_docker.yml@v1
    secrets:
      dockerhub-username: ${{ secrets.DOCKERHUB_USERNAME }}
      dockerhub-token: ${{ secrets.DOCKERHUB_TOKEN }}
    with:
      name: Production
      target: production
      publish: false
      image: gmmcal/ynab:production

  # LINT
  rubocop:
    name: Lint
    uses: gmmcal/gmmcal-reusable-workflows/.github/workflows/_lint.yml@v1
    with:
      name: Rubocop
      image: "gmmcal/ynab:test-${{ github.event.number }}-${{ github.run_number }}"
      command: bin/rubocop
    needs: build

  reek:
    name: Lint
    uses: gmmcal/gmmcal-reusable-workflows/.github/workflows/_lint.yml@v1
    with:
      name: Reek
      image: "gmmcal/ynab:test-${{ github.event.number }}-${{ github.run_number }}"
      command: bundle exec reek --config .reek.yml 1
    needs: build

  brakeman:
    name: Lint
    uses: gmmcal/gmmcal-reusable-workflows/.github/workflows/_lint.yml@v1
    with:
      name: Brakeman
      image: "gmmcal/ynab:test-${{ github.event.number }}-${{ github.run_number }}"
      command: bin/brakeman
    needs: build

  bundler-audit:
    name: Lint
    uses: gmmcal/gmmcal-reusable-workflows/.github/workflows/_lint.yml@v1
    with:
      name: Bundler Audit
      image: "gmmcal/ynab:test-${{ github.event.number }}-${{ github.run_number }}"
      command: bundle exec bundle-audit check --update
    needs: build

  # TESTS
  tests:
    name: Tests
    uses: gmmcal/gmmcal-reusable-workflows/.github/workflows/_tests.yml@v1
    with:
      image: "gmmcal/ynab:test-${{ github.event.number }}-${{ github.run_number }}"
      command: bundle exec rails test
    needs: build
